name: dloe
favicon: null
layout_spectrum: 0.305776838446036
typography_spectrum: 0.38456794200465083
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2828183511737734
  lightness: 0.82851945864968
  saturation: 0.3775636269710958
  rhythmicContrast: 0.44842361751943827
purpose: []
